fastcgi-daemon:
  extends:
    file: docker-fastcgi-daemon/docker-compose.yml
    service: fastcgi-daemon
  volumes:
    - ./bin:data

nginx:
  extends:
    file: docker-fastcgi-daemon/docker-compose.yml
    service: nginx
  volumes:
    - ./bin/nginx.conf:/etc/nginx/conf.d/default.conf
    - ./bin/logs:/var/log/nginx

builder:
  extends:
    file: docker-fastcgi-daemon/docker-compose.yml
    service: builder
  volumes:
    - ./src:/src
    - ./bin:/target
  working_dir: "/src"
  command: ["make"]
